version: "3.9"

services:
  web:
    build:
      context: .
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: planetarium
      POSTGRES_USER: planet
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
