# Generated by Django 5.2.1 on 2025-05-30 16:03

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="showsession",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.show_image_file_path
            ),
        ),
    ]
