# Generated by Django 5.2.1 on 2025-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_showsession_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/shows/"),
        ),
    ]
